### ISSUE TITLE
Error: Traceback (Most Recent Call Last)

### ISSUE THREAD

**Issue by Rexcuni** [boriskurikhin/UnfollowGram#1]
Hi @boriskurikhin 

I tried UnfollowGram a while ago and it worked really well.
However, after Instagram updated its algorithm, it looks like the program can't work anymore.

So, after I used the program again, the following error message appeared:

`rexcuni@backtrack UnfollowGram % python3 unfollow.py 
Traceback (most recent call last):
  File "unfollow.py", line 151, in <module>
    logged_in = login()
  File "unfollow.py", line 133, in login
    great_success = json.loads(response.text)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)`

I hope you update UnfollowGram to make it work better.

**Comment by boriskurikhin** [comment]
Thanks for opening the ticket, I'll have a look at this error as soon as I get some time.
